apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: code
            operator: In
            values:
            - codeforaffinity
  containers:
  - name: containerforaffinity
    image: nginx
