apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: code
              operator: "Exists"
              values:
              - nodeaffinity
  containers:
    - name: containerforaffinity
      image: nginx
