apiVersion: v1
kind: Pod
metadata:
  name: antiafinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: code
                operator: NotIn
                values:
                - antiafinity
  containers:
  - name: containerforanti
    image: nginx