apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: code
            operator: NotIn
            values:
            - codeforantiaffinity
  containers:
  - name: containerforanti
    image: nginx